export const bookCategories = [
    // Fiction
    "Adventure",
    "Anthology",
    "Chick Lit",
    "Classics",
    "Crime",
    "Cyberpunk",
    "Detective & Mystery",
    "Dystopian",
    "Epic",
    "Fantasy",
    "Graphic Novel",
    "Historical Fiction",
    "Horror",
    "Humor & Satire",
    "Literary Fiction",
    "Magical Realism",
    "Mystery",
    "Paranormal",
    "Realist Fiction",
    "Romance",
    "Science Fiction",
    "Steampunk",
    "Suspense & Thriller",
    "Urban Fiction",
    "Western",

    // Children & Teens
    "Baby & Toddler Books",
    "Board Books",
    "Children’s Fiction",
    "Children’s Nonfiction",
    "Early Readers",
    "Middle Grade",
    "Picture Books",
    "Young Adult",

    // Non-Fiction
    "Autobiography",
    "Biography",
    "Business & Economics",
    "Crafts & Hobbies",
    "Cooking & Food",
    "Education & Teaching",
    "Essays",
    "Health & Fitness",
    "History",
    "Home & Garden",
    "Humor",
    "Journalism & Nonfiction",
    "Law",
    "Medical",
    "Memoir",
    "Music",
    "Nature & Ecology",
    "Parenting & Relationships",
    "Philosophy",
    "Politics & Social Sciences",
    "Psychology",
    "Reference",
    "Religion & Spirituality",
    "Science & Math",
    "Self-Help",
    "Sports & Recreation",
    "Technology & Engineering",
    "Travel",

    // Specialized & Academic
    "Anthropology",
    "Architecture",
    "Art & Photography",
    "Astronomy",
    "Business & Management",
    "Chemical Engineering",
    "Computer Science",
    "Economics",
    "Education Theory",
    "Environmental Science",
    "Graphic Design",
    "Linguistics",
    "Mathematics",
    "Neuroscience",
    "Physics",
    "Political Science",
    "Psychiatry",
    "Sociology",
    "Statistics",

    // Cultural & Regional
    "African Literature",
    "Asian Literature",
    "Caribbean Literature",
    "European Literature",
    "Latin American Literature",
    "Middle Eastern Literature",

    // Niche & Others
    "Comics & Graphic Novels",
    "Essays & Opinion",
    "Holiday & Seasonal",
    "Journals & Notebooks",
    "Mythology & Folklore",
    "New Age & Spirituality",
    "True Crime",
    "Workbooks & Study Aids",
    "Zines",
];
