export const bookCategories = [
    // Fiction
    "Adventure",
    "Anthology",
    "Chick Lit",
    "Classics",
    "Crime",
    "Cyberpunk",
    "Detective & Mystery",
    "Dystopian",
    "Epic",
    "Fantasy",
    "Graphic Novel",
    "Historical Fiction",
    "Horror",
    "Humor & Satire",
    "Literary Fiction",
    "Magical Realism",
    "Mystery",
    "Paranormal",
    "Realist Fiction",
    "Romance",
    "Science Fiction",
    "Steampunk",
    "Suspense & Thriller",
    "Urban Fiction",
    "Western",

    // Children & Teens
    "Baby & Toddler Books",
    "Board Books",
    "Children’s Fiction",
    "Children’s Nonfiction",
    "Early Readers",
    "Middle Grade",
    "Picture Books",
    "Young Adult",

    // Non-Fiction
    "Autobiography",
    "Biography",
    "Business & Economics",
    "Crafts & Hobbies",
    "Cooking & Food",
    "Education & Teaching",
    "Essays",
    "Health & Fitness",
    "History",
    "Home & Garden",
    "Humor",
    "Journalism & Nonfiction",
    "Law",
    "Medical",
    "Memoir",
    "Music",
    "Nature & Ecology",
    "Parenting & Relationships",
    "Philosophy",
    "Politics & Social Sciences",
    "Psychology",
    "Reference",
    "Religion & Spirituality",
    "Science & Math",
    "Self-Help",
    "Sports & Recreation",
    "Technology & Engineering",
    "Travel",

    // Specialized & Academic
    "Anthropology",
    "Architecture",
    "Art & Photography",
    "Astronomy",
    "Business & Management",
    "Chemical Engineering",
    "Computer Science",
    "Economics",
    "Education Theory",
    "Environmental Science",
    "Graphic Design",
    "Linguistics",
    "Mathematics",
    "Neuroscience",
    "Physics",
    "Political Science",
    "Psychiatry",
    "Sociology",
    "Statistics",

    // Cultural & Regional
    "African Literature",
    "Asian Literature",
    "Caribbean Literature",
    "European Literature",
    "Latin American Literature",
    "Middle Eastern Literature",

    // Niche & Others
    "Comics & Graphic Novels",
    "Essays & Opinion",
    "Holiday & Seasonal",
    "Journals & Notebooks",
    "Mythology & Folklore",
    "New Age & Spirituality",
    "True Crime",
    "Workbooks & Study Aids",
    "Zines",
];


export const languages = [
    "Afar",
    "Abkhaz",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Aymara",
    "Azerbaijani",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan",
    "Chamorro",
    "Chechen",
    "Chichewa",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi",
    "Dutch",
    "Dzongkha",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fula",
    "Galician",
    "Ganda",
    "Georgian",
    "German",
    "Greek",
    "Guarani",
    "Gujarati",
    "Haitian Creole",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Icelandic",
    "Ido",
    "Igbo",
    "Indonesian",
    "Interlingua",
    "Interlingue",
    "Inuktitut",
    "Inupiaq",
    "Irish",
    "Italian",
    "Japanese",
    "Javanese",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu",
    "Kinyarwanda",
    "Kirghiz",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama",
    "Latin",
    "Luxembourgish",
    "Luganda",
    "Limburgish",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Manx",
    "Maori",
    "Marathi",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "Navajo",
    "Ndonga",
    "Nepali",
    "North Ndebele",
    "Northern Sami",
    "Norwegian",
    "Occitan",
    "Ojibwa",
    "Oriya",
    "Oromo",
    "Ossetian",
    "Pali",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romanian",
    "Romansh",
    "Rundi",
    "Russian",
    "Samoan",
    "Sango",
    "Sanskrit",
    "Sardinian",
    "Serbian",
    "Shona",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Somali",
    "Southern Sotho",
    "Spanish",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tagalog",
    "Tahitian",
    "Tajik",
    "Tamil",
    "Tatar",
    "Telugu",
    "Thai",
    "Tibetan",
    "Tigrinya",
    "Tonga",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Twi",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Welsh",
    "Wolof",
    "Western Frisian",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang",
    "Zulu"
  ];
  